#+TITLE: A test file for the *Org-edu-HTML* exporter
#+AUTHOR: Marcin Borkowski
#+DATE: 2014-10-31
#+EDU_CHECK_NAME: Did I get it right?
#+EDU_OK_NAME: How cool is that!
#+EDU_WRONG_NAME: You don't seem to "get" it, right?
#+EDU_SHOW: Show me what's hidden here!
#+EDU_HIDE: Hide the answer again.

* Examples
** Single-choice question
And now a single-choice question:
#+ATTR_EDU: :test sct
- [ ] Wrong answer again.
- [ ] Boooo!
- [X] That's good!
  #+BEGIN_COMMENT_OK
  This is a remark for the good answer.  (And a very long one, for
  that matter.  One that does not fit in a single line of text.
  Actually, it spans more than one line.  Two lines, two be more
  precise.)
  #+END_COMMENT_OK
  #+BEGIN_COMMENT_WRONG
  This is a remark in case someone gives a wrong answer.
  #+END_COMMENT_WRONG
- [ ] That's wrong.
  #+BEGIN_COMMENT_OK
  This is a remark for the good answer.
  #+END_COMMENT_OK
  #+BEGIN_COMMENT_WRONG
  This is a remark in case someone gives a wrong answer.
  #+END_COMMENT_WRONG

** Multiple-choice question
A multiple-choice question:
#+ATTR_EDU: :test mct
- [ ] Wrong answer.
  #+BEGIN_COMMENT_OK
  This is a remark for the good answer.
  #+END_COMMENT_OK
  #+BEGIN_COMMENT_WRONG
  This is a remark in case someone gives a wrong answer.
  #+END_COMMENT_WRONG
- [ ] Another wrong answer.
- [X] Right answer.
  #+BEGIN_COMMENT_OK
  This is a remark for the good answer.
  #+END_COMMENT_OK
  #+BEGIN_COMMENT_WRONG
  This is a remark in case someone gives a wrong answer.
  #+END_COMMENT_WRONG
- [X] Another right answer.

** Cloze test
A cloze test:
#+BEGIN_CLOZE
A _cloze_ test is a test where the _student|learner_ has to type a
missing _word|phrase_.
#+BEGIN_COMMENT_OK
This is the "OK" comment.
#+END_COMMENT_OK
#+BEGIN_COMMENT_WRONG
This is the "wrong" comment.
#+END_COMMENT_WRONG
#+BEGIN_HIDDEN
This is a hint for this problem!
#+END_HIDDEN
#+END_CLOZE
** Show the answer
Now think about this question and press the button when you think you know the answer.
#+BEGIN_HIDDEN :show Show me the hint! :hide Hide the hint again!
This is the secret answer.  Hopefully you got it right!
#+END_HIDDEN
** Single-choice drop-down					      :split:
3 squared equals
#+ATTR_EDU: :test select
- [ ] 1
- [ ] 3
- [X] 9
- [ ] 27
and that's it!

3 cubed equals
#+ATTR_EDU: :test select
- [ ] 1
- [ ] 3
- [ ] 9
- [X] 27
and that's a bit more difficult.
* COMMENT Config
#+OPTIONS: toc:nil num:nil
* COMMENT Lisp
(progn
  (if (get-buffer "oeh-test.html")
      (kill-buffer "oeh-test.html"))
  (org-export-to-buffer 'edu-html "oeh-test.html")
  (write-file "oeh-test.html")
  (view-mode 1))
