#+TITLE: Org-edu-HTML: A variant of the Emacs Org-mode HTML exporter for educational materials
#+AUTHOR: Marcin Borkowski <mbork@mbork.pl>

* Usage
Prepare a normal Org-mode file.  You can embed single and multiple choice tests and cloze tests in the document.

** Options
Currently, three options are recognized.  They allow to specify the text on the button ("Check" by default) and the texts displayed when the answer is right or wrong ("OK!" and "Wrong..." by default).  To change them, write something like this somewehere in the Org file:
#+BEGIN_EXAMPLE
#+EDU_CHECK_NAME: Did I get it right?
#+EDU_OK_NAME: How cool is that!
#+EDU_WRONG_NAME: You don't seem to "get" it, right?
#+END_EXAMPLE

** Multiple choice tests
:PROPERTIES:
:ID:       ac9120a9-4b34-4d9b-be32-9f89715afe77
:END:
Write a plain list with checkboxes; mark correct answers.  Put a line saying
: #+ATTR_EDU: :test mct
before the list.

You may embed special blocks called =COMMENT_OK= and =COMMENT_WRONG= within any of the answers (items in the list).  These will be shown when the user gave a correct/wrong answer respectively.

Example:
#+BEGIN_EXAMPLE
A multiple-choice question:
#+ATTR_EDU: :test mct
- [ ] Wrong answer.
  #+BEGIN_COMMENT_OK
  This is a remark for the good answer.
  #+END_COMMENT_OK
  #+BEGIN_COMMENT_WRONG
  This is a remark in case someone gives a wrong answer.
  #+END_COMMENT_WRONG
- [ ] Another wrong answer.
- [X] Right answer.
  #+BEGIN_COMMENT_OK
  This is a remark for the good answer.
  #+END_COMMENT_OK
  #+BEGIN_COMMENT_WRONG
  This is a remark in case someone gives a wrong answer.
  #+END_COMMENT_WRONG
- [X] Another right answer.
#+END_EXAMPLE

** Single choice tests
Multiple choice tests work exactly like [[id:ac9120a9-4b34-4d9b-be32-9f89715afe77][multiple choice tests]]: the only difference is that you should put
: #+ATTR_EDU: :test mct
before the list.  The behavior of a SCT when more than one answer is marked as correct is unspecified (currently, /any/ of the answers marked as correct will be accepted).

Alternatively, you can use HTML drop-down lists instead of radio buttons for SCTs; just say
: #+ATTR_EDU: :test select
before the list.

** Cloze tests
Cloze tests are denoted by a special block =CLOZE=.  In it, underline text fragments which should be rendered as blanks.  You can separate variants with a vertical bar (=|=).  Example:
: #+BEGIN_CLOZE
: A _cloze_ test is a test where the _student|learner_ has to type a missing _word|phrase_.
: #+END_CLOZE

* Known bugs and missing features
See [[file:TODO.org][TODO.org]].
